# Generated by Django 6.0.3 on 2026-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=300, verbose_name="Razão social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Nome fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Inscrição estadual"
                    ),
                ),
                (
                    "porte",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ME", "Microempresa"),
                            ("PE", "Pequeno porte"),
                            ("MD", "Médio porte"),
                            ("GR", "Grande porte"),
                        ],
                        max_length=2,
                        verbose_name="Porte",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("AT", "Ativa"),
                            ("IN", "Inativa"),
                            ("SU", "Suspensa"),
                            ("EX", "Extinta"),
                        ],
                        default="AT",
                        max_length=2,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "ramo_atividade",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ramo de atividade"
                    ),
                ),
                (
                    "data_fundacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de fundação"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="empresas/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="Site")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Estado (UF)"
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="Organizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=300, verbose_name="Nome")),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=30, verbose_name="Sigla"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONG", "ONG"),
                            ("GOV", "Órgão governamental"),
                            ("MIL", "Militar / policial"),
                            ("INT", "Internacional"),
                            ("ASS", "Associação"),
                            ("SIN", "Sindicato"),
                            ("PAR", "Partido político"),
                            ("OUT", "Outro"),
                        ],
                        max_length=3,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("AT", "Ativa"), ("IN", "Inativa"), ("EX", "Extinta")],
                        default="AT",
                        max_length=2,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "area_atuacao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Área de atuação"
                    ),
                ),
                (
                    "data_fundacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de fundação"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizacoes/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("site", models.URLField(blank=True, verbose_name="Site")),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Estado (UF)"
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "organizacoes_vinculadas",
                    models.ManyToManyField(
                        blank=True,
                        to="pessoas.organizacao",
                        verbose_name="Organizações vinculadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organização",
                "verbose_name_plural": "Organizações",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=300, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                ("rg", models.CharField(blank=True, max_length=20, verbose_name="RG")),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("N", "Não informado"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SO", "Solteiro(a)"),
                            ("CA", "Casado(a)"),
                            ("DI", "Divorciado(a)"),
                            ("VI", "Viúvo(a)"),
                            ("UE", "União Estável"),
                        ],
                        max_length=2,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        blank=True,
                        default="Brasileira",
                        max_length=100,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "naturalidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Naturalidade"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pessoas/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=10, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Estado (UF)"
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pessoas",
                        to="pessoas.empresa",
                        verbose_name="Empresas vinculadas",
                    ),
                ),
                (
                    "organizacoes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pessoas",
                        to="pessoas.organizacao",
                        verbose_name="Organizações vinculadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
                "ordering": ["nome_completo"],
            },
        ),
    ]
