# Generated by Django 6.0.3 on 2026-03-21 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("pessoas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("OBS", "Observação"),
                            ("EVE", "Evento"),
                            ("INC", "Incidente"),
                            ("RES", "Reunião"),
                            ("OUT", "Outro"),
                        ],
                        default="OBS",
                        max_length=3,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_fato", models.DateTimeField(verbose_name="Data/hora do fato")),
                (
                    "local",
                    models.CharField(blank=True, max_length=300, verbose_name="Local"),
                ),
                (
                    "fonte",
                    models.CharField(blank=True, max_length=300, verbose_name="Fonte"),
                ),
                (
                    "confidencial",
                    models.BooleanField(default=False, verbose_name="Confidencial"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fatos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fatos",
                        to="documentos.documento",
                        verbose_name="Documentos relacionados",
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fatos",
                        to="pessoas.empresa",
                        verbose_name="Empresas envolvidas",
                    ),
                ),
                (
                    "organizacoes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fatos",
                        to="pessoas.organizacao",
                        verbose_name="Organizações envolvidas",
                    ),
                ),
                (
                    "pessoas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fatos",
                        to="pessoas.pessoa",
                        verbose_name="Pessoas envolvidas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fato",
                "verbose_name_plural": "Fatos",
                "ordering": ["-data_fato"],
            },
        ),
        migrations.CreateModel(
            name="Memoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "data_memoria",
                    models.DateField(blank=True, null=True, verbose_name="Data"),
                ),
                ("fixada", models.BooleanField(default=False, verbose_name="Fixada")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memorias_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True, related_name="memorias", to="pessoas.empresa"
                    ),
                ),
                (
                    "organizacoes",
                    models.ManyToManyField(
                        blank=True, related_name="memorias", to="pessoas.organizacao"
                    ),
                ),
                (
                    "pessoas",
                    models.ManyToManyField(
                        blank=True, related_name="memorias", to="pessoas.pessoa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Memória",
                "verbose_name_plural": "Memórias",
                "ordering": ["-fixada", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "data_referencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de referência"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relatorios_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True, related_name="relatorios", to="documentos.documento"
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True, related_name="relatorios", to="pessoas.empresa"
                    ),
                ),
                (
                    "fatos",
                    models.ManyToManyField(
                        blank=True, related_name="relatorios", to="registros.fato"
                    ),
                ),
                (
                    "organizacoes",
                    models.ManyToManyField(
                        blank=True, related_name="relatorios", to="pessoas.organizacao"
                    ),
                ),
                (
                    "pessoas",
                    models.ManyToManyField(
                        blank=True, related_name="relatorios", to="pessoas.pessoa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
                "ordering": ["-criado_em"],
            },
        ),
    ]
