# Generated by Django 6.0.3 on 2026-03-21 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pessoas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("WORD", "Word (.docx)"),
                            ("EXCEL", "Excel (.xlsx)"),
                            ("ODT", "LibreOffice (.odt)"),
                            ("IMG", "Imagem"),
                            ("OUT", "Outro"),
                        ],
                        max_length=5,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REL", "Relatório"),
                            ("LAU", "Laudo"),
                            ("OFF", "Ofício"),
                            ("CON", "Contrato"),
                            ("ID", "Documento de identificação"),
                            ("FIN", "Financeiro"),
                            ("JUD", "Judicial"),
                            ("OUT", "Outro"),
                        ],
                        max_length=3,
                        verbose_name="Categoria",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do documento"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentos",
                        to="pessoas.empresa",
                        verbose_name="Empresas relacionadas",
                    ),
                ),
                (
                    "organizacoes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentos",
                        to="pessoas.organizacao",
                        verbose_name="Organizações relacionadas",
                    ),
                ),
                (
                    "pessoas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documentos",
                        to="pessoas.pessoa",
                        verbose_name="Pessoas relacionadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_documento"],
            },
        ),
    ]
