"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from decouple import config,Csv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOST', default='127.0.0.1,localhost', cast=Csv())



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps do projeto
    'accounts',
    'pessoas',
    'documentos',
    'registros',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

import os
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'templates')]

import os

# Onde os arquivos enviados serão salvos no disco
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL pública para acessar esses arquivos no navegador
MEDIA_URL = '/media/'

# Redireciona para o login quando acesso não autenticado
LOGIN_URL          = '/accounts/login/'
LOGIN_REDIRECT_URL = '/pessoas/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Limite de 100 MB por upload
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

# ── Segurança de sessão e cookies ─────────────────────────────
SESSION_COOKIE_HTTPONLY  = True   # JS não acessa o cookie de sessão
SESSION_COOKIE_SAMESITE  = 'Lax'  # Proteção contra CSRF entre sites
CSRF_COOKIE_HTTPONLY     = False  # Necessário para o Django funcionar
CSRF_COOKIE_SAMESITE     = 'Lax'

# Tempo de sessão — 8 horas (expira ao fechar o navegador se False)
SESSION_COOKIE_AGE       = 28800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ── Proteção contra clickjacking ──────────────────────────────
X_FRAME_OPTIONS = 'DENY'

# ── Força HTTPS (apenas se configurar certificado local) ──────
# SECURE_SSL_REDIRECT = True  # descomente só se usar HTTPS
